version: '3'
services:
  web:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./default.conf:/etc/nginx/conf.d/default.conf"
      - "./domain.key:/etc/nginx/domain.key"
      - "./domain.crt:/etc/nginx/domain.crt"